### ISSUE TITLE
Attach JAR file to GitHub release

### ISSUE THREAD

**Issue by asmith60** [GDATASoftwareAG/Graylog-Plugin-AlertManager-Callback#5]
Would it be possible to attach the JAR file output by the build process to each corresponding release? 

You provide great instructions for building the JAR on your own :) , but it would be easier to consume this plugin via automation if I could point to a public GitHub release to download the JAR. Below is a link to an example release on an example plugin that shows what I am talking about.
 
https://github.com/cvtienhoven/graylog-plugin-aggregates/releases/tag/2.4.0

**Comment by StefanHufschmidt** [comment]
@asmith60 I struggled a bit with Travis but now it should work as expected and you can download a jar from the releases page.
