### ISSUE TITLE
Alerts disregarded when condition grace set to zero

### ISSUE THREAD

**Issue by aither64** [GDATASoftwareAG/Graylog-Plugin-AlertManager-Callback#9]
When condition grace in graylog is set to zero, the payload sent to alertmanager contains startsAt and endsAt set to the [same time](https://github.com/GDATASoftwareAG/Graylog-Plugin-AlertManager-Callback/blob/master/src/main/java/de/gdata/mobilelab/alertmanagercallback/AlertManagerPayloadBuilder.java#L121). Alertmanager seems to disregard these alerts. You could say that they are already resolved anyway, so it makes sense.

Would it be possible to always set endsAt at least one minute to the future?

**Comment by StefanHufschmidt** [comment]
@aither64 nice finding. Sorry for the late answer. I've requested @knackaron to fix the failing test and add a test for the behavior you described.

**Comment by StefanHufschmidt** [comment]
@aither64 we've just released a hotfix related to this issue. It should be fixed now.
